class Spanish_Utils:
    add_spanish = {
        'NULL': 'NULL',
        'Geriatric Medicine': 'Geriatric Medicine / medicina Geriatrica',
        'Family Medicine': 'Family Medicine / Medicina Familiar',
        'Internal Medicine': 'Internal Medicine / Medicina interna',
        'Pediatrics': 'Pediatrics / Pediatría',
        'Ophthalmology': 'Ophthalmology / Oftalmología',
        'Optometry': 'Optometry / Optometría',
        'Orthopaedic Surgery': 'Orthopaedic Surgery / Cirugía ortopédica',
        'Pain Medicine': 'Pain Medicine / Medicina del dolor',
        'Physician Assistant': 'Physician Assistant / Asistente medico',
        'Physician Assistant PCP': 'Physician Assistant PCP / Auxiliar médico',
        'Acupuncture': 'Acupuncture / Acupuntura',
        'Adolescent Medicine': 'Adolescent Medicine / Medicina del adolescente',
        'Advanced Heart Failure and Transplant Cardiology': 'Advanced Heart Failure and Transplant Cardiology',
        'Allergy and Immunology': 'Allergy And Immunology / Alergia e inmunología',
        'Anesthesiology': 'Anesthesiology / Anestesiología',
        'Audiology': 'Audiology / Audiología',
        'Bariatric Surgery': 'Bariatric Surgery / Cirugía bariátrica',
        'Breast Surgery': 'Breast Surgery / Cirugía de mamas',
        'Burn Surgery': 'Burn Surgery / Cirugía de quemaduras',
        'Cardiac Electrophysiology': 'Cardiac Electrophysiology / Electrofisiología cardiaca',
        'Cardiac Surgery': 'Cardiac Surgery / Cirugía cardiaca',
        'Cardiovascular Disease': 'Cardiovascular Disease / Enfermedad cardiovascular',
        'Certified Nurse Midwife': 'Certified Nurse Midwife / Enfermera partera certificada',
        'Child Abuse Pediatrics': 'Child Abuse Pediatrics / Pediatría',
        'Chiropractic Medicine': 'Chiropractic Medicine / Medicina Quiropráctica',
        'Clinical Biochemical Genetics': 'Clinical Biochemical Genetics / Genética Bioquímica Clínica',
        'Clinical Genetics': 'Clinical Genetics / Genética clínica',
        'Clinical Neurophysiology': 'Clinical Neurophysiology / Neurofisiología clínica',
        'Colon and Rectal Surgery': 'Colon And Rectal Surgery / Cirugía de colon y recto',
        'Critical Care Medicine': 'Critical Care Medicine / Medicina de Terapia Intensiva',
        'Dermatology': 'Dermatology / Dermatología',
        'Dermatopathology': 'Dermatopathology / dermatopatología',
        'Developmental and Behavioral Pediatrics': 'Developmental And Behavioral Pediatrics / Pediatría del Desarrollo y el comportamiento',
        'Emergency Medicine': 'Emergency Medicine / Medicina de emergencia',
        'Endocrinology Diabetes and Metabolism': 'Endocrinology Diabetes and Metabolism / Endocrinología Diabetes y Metabolismo',
        'Family Medicine - Specialist': 'Family Medicine - Specialist / Medicina familiar - Especialista',
        'Female Pelvic Reproductive Surgery': 'Female Pelvic Reproductive Surgery / Cirugía reproductiva pélvica femenina',
        'Gastroenterology': 'Gastroenterology / Gastroenterología',
        'General Practice - Specialist': 'General Practice - Specialist / Práctica General - Especialista',
        'General Practice': 'General Practice / Medicina general',
        'General Surgery': 'General Surgery / Cirugía General',
        'Gynecologic Oncology': 'Gynecologic Oncology / Oncología ginecológica',
        'Gynecology': 'Gynecology / Ginecología',
        'Hand Surgery': 'Hand Surgery / Cirugía de la mano',
        'Hematology': 'Hematology / Hematología',
        'Hematology Oncology': 'Hematology Oncology / Hematología Oncología',
        'Hospice and Palliative Medicine': 'Hospice And Palliative Medicine / Hospicio y medicina paliativa',
        'Infectious Diseases': 'Infectious Diseases / Enfermedades infecciosas',
        'Internal Medicine - Specialist': 'Internal Medicine - Specialist / Medicina interna - Especialista',
        'Interventional Cardiology': 'Interventional Cardiology / Cardiología intervencionista',
        'Interventional Radiology': 'Interventional Radiology / Radiología intervencional',
        'Licensed Dietetic Nutritionist': 'Licensed Dietetic Nutritionist / Licenciado en nutrición y dietética',
        'Maternal - Fetal Medicine': 'Maternal - Fetal Medicine / Medicina maternofetal',
        'Medical Acupuncture': 'Medical Acupuncture / Acupuntura Médica',
        'Medical Genetics': 'Medical Genetics / Genética médica',
        'Medical Oncology': 'Medical Oncology / Oncología médica',
        'Neonatal-Perinatal Medicine': 'Neonatal-Perinatal Medicine / Medicina neonatal y perinatal',
        'Nephrology': 'Nephrology / Nefrología',
        'Neurodevelopmental Disabilities': 'Neurodevelopmental Disabilities / Discapacidades del neurodesarrollo',
        'Neurology': 'Neurology / Neurología',
        'Neurosurgery': 'Neurosurgery / Neurocirugía',
        'Nutritionist': 'Nutritionist / Nutricionista',
        'Obstetrics and Gynecology': 'Obstetrics and Gynecology / Ginecología',
        # 'Ophthalmology': 'Ophthalmology / Oftalmología ',
        # 'Optometry': 'Optometry / Optometría',
        'Oral & Maxillofacial Surgery': 'Oral & Maxillofacial Surgery / Cirugía Oral y Maxilofacial',
        # 'Orthopaedic Surgery': 'Orthopaedic Surgery / Cirugía ortopédica',
        'Orthopedic Oncology': 'Orthopedic Oncology / Oncología ortopédica',
        'Otolaryngology': 'Otolaryngology / Otorrinolaringología',
        # 'Pain Medicine': 'Pain Medicine / Medicina del dolor',
        'Pediatric Allergy and Immunology': 'Pediatric Allergy And Immunology / Alergia e inmunología',
        'Pathology - Anatomic and Clinical': 'Pathology - Anatomic and Clinical / Patología - Anatómica y Clínica',
        'Pediatric Cardiac Surgery': 'Pediatric Cardiac Surgery / Cirugía cardiaca',
        'Pediatric Cardiology': 'Pediatric Cardiology / Cardiología pediátrica',
        'Pediatric Clinical Genetics': 'Pediatric Clinical Genetics / Genética clínica',
        'Pediatric Critical Care Medicine': 'Pediatric Critical Care Medicine / Medicina de Terapia Intensiva',
        'Pediatric Dermatology': 'Pediatric Dermatology / Dermatología',
        'Pediatric Endocrinology': 'Pediatric Endocrinology / Endocrinología pediátrica',
        'Pediatric Gastroenterology': 'Pediatric Gastroenterology / Gastroenterología',
        'Pediatric Genetics': 'Pediatric Genetics / Genética pediátrica',
        'Pediatric Hematology-Oncology': 'Pediatric Hematology-Oncology / Hematología y oncología pediátrica',
        'Pediatric Infectious Diseases': 'Pediatric Infectious Diseases / Enfermedades infecciosas',
        'Pediatric Nephrology': 'Pediatric Nephrology / Nefrología',
        'Pediatric Neurodevelopmental Disabilities': 'Pediatric Neurodevelopmental Disabilities / Discapacidades del neurodesarrollo',
        'Pediatric Neurology': 'Pediatric Neurology / Neurología',
        'Pediatric Neurosurgery': 'Pediatric Neurosurgery / Neurocirugía',
        'Pediatric Ophthalmology': 'Pediatric Ophthalmology / Oftalmología',
        'Pediatric Orthopaedic Surgery': 'Pediatric Orthopaedic Surgery / Cirugía ortopédica',
        'Pediatric Otolaryngology': 'Pediatric Otolaryngology / Otorrinolaringología',
        'Pediatric Plastic and Reconstructive Surgery': 'Pediatric Plastic And Reconstructive Surgery / Cirugía plástica y reconstructiva pediátrica',
        'Pediatric Pulmonology': 'Pediatric Pulmonology / Neumología pediátrica',
        'Pediatric Rehabilitation Medicine': 'Pediatric Rehabilitation Medicine / Medicina de rehabilitación pediátrica',
        'Pediatric Rheumatology': 'Pediatric Rheumatology / Reumatología pediátrica',
        'Pediatric Surgery': 'Pediatric Surgery / Cirugía pediátrica',
        'Pediatric Transplant Hepatology': 'Pediatric Transplant Hepatology / Hepatología pediátrica y trasplante',
        'Pediatric Urology': 'Pediatric Urology / Urología pediátrica',
        'Pediatrics - Specialist': 'Pediatrics - Specialist / Pediatría - Especialista',
        'Physical Medicine and Rehabilitation': 'Physical Medicine And Rehabilitation / Medicina física y rehabilitación',
        # 'Physician Assistant': 'Physician Assistant / Asistente medico',
        'Plastic Surgery': 'Plastic Surgery / Cirugía plástica',
        'Podiatry': 'Podiatry / Podiatría',
        'Psychiatry': 'Psychiatry / Psiquiatría',
        'Pulmonary Disease': 'Pulmonary Disease / Enfermedad pulmonar',
        'Preventive Medicine': 'Preventive Medicine / Medicina Preventiva',
        'Radiation Oncology': 'Radiation Oncology / Oncología radioterápica',
        'Registered Dietician': 'Registered Dietician / Dietista registrada',
        'Reproductive Endocrinology and Infertility': 'Reproductive Endocrinology And Infertility / Endocrinología de la reproducción e infertilidad',
        'Rheumatology': 'Rheumatology / Reumatología',
        'Sleep Medicine': 'Sleep Medicine / Medicina del sueño',
        'Spinal Cord Injury Medicine': 'Spinal Cord Injury Medicine / Medicina para lesiones de la médula espinal',
        'Sports Medicine': 'Sports Medicine / Medicina deportiva',
        'Surgical Critical Care': 'Surgical Critical Care / Cuidados intensivos quirúrgicos',
        'Surgical Oncology': 'Surgical Oncology / Oncología quirúrgica',
        'Thoracic Surgery': 'Thoracic Surgery / Cirugía torácica',
        'Transplant Hepatology': 'Transplant Hepatology / Hepatología de trasplantes',
        'Transplant Surgery': 'Transplant Surgery / Cirugía de trasplante',
        'Trauma Surgery': 'Trauma Surgery / Cirugia de trauma',
        'Undersea and Hyperbaric Medicine': 'Undersea And Hyperbaric Medicine / Medicina Submarina e Hiperbárica',
        'Urogynecology': 'UroGynecology / Ginecología',
        'Urology': 'Urology / Urología',
        'Vascular and Interventional Radiology': 'Vascular and Interventional Radiology / Radiología intervencional',
        'Vascular Neurology': 'Vascular Neurology / Neurología',
        'Vascular Surgery': 'Vascular Surgery / Cirugía vascular',
        'Ambulance & Van Transport': 'Ambulance & Van Transport / Transporte de ambulancias y furgonetas',
        'Ambulatory Surgery Center': 'Ambulatory Surgery Center / Centro de Cirugía Ambulatoria',
        'Cardiac Monitoring': 'Cardiac Monitoring / Monitoreo cardíaco',
        'Diabetic Prevention Program': 'Diabetic Prevention Program / Programa de Prevención de la Diabetes',
        'Dialysis': 'Dialysis / Diálisis',
        'Durable Medical Equipment': 'Durable Medical Equipment / Equipo médico duradero',
        'Home Health': 'Home Health / Salud en el hogar',
        'Hospice': 'Hospice / Hospicio',
        'Hospital': 'Hospital / Hospital',
        'Infusion/Injectables': 'Infusion/Injectables / Infusión/Inyectables',
        'Laboratory': 'Laboratory / Laboratorio',
        'Orthotics & Prosthetics': 'Orthotics & Prosthetics / Ortesis y prótesis',
        'Pediatric Hospital': 'Pediatric Hospital / Hospital / Hospital Pediátrico / Hospital',
        'Radiology': 'Radiology / radiología',
        'Rehab Hospital': 'Rehab Hospital / Hospital',
        'Rehabilitation': 'Rehabilitation / Rehabilitación',
        'Skilled Nursing Facility': 'Skilled Nursing Facility / Centro de enfermería especializado',
        'Sleep Center': 'Sleep Center / Centro del Sueño',
        'Urgent Care Centers': 'Urgent Care Centers / Centros de atención de urgencias',
        'Pharmacy': 'Pharmacy / Farmacia',
        'Clinic/Center - Federally Qualified Health Center (FQHC)': 'Clinic/Center - Federally Qualified Health Center (FQHC) / Clínica/Centro - Servicios su-ministrados por un Centro de Salud con Calificación Federal (FQHC, en inglés)',
        'Eyewear Supplier (Equipment Not The Service)': 'Eyewear Supplier (Equipment Not The Service) / Proveedor de lentes (equipo, no el servicio)',
        'Eyewear Supplier (Equipment not the service) - Eyewear Supplier (Equipment not the service)': 'Eyewear Supplier (Equipment Not The Service) / Proveedor de lentes (equipo, no el servicio)',
        'Ophthalmology - Ophthalmology': 'Ophthalmology / Oftalmología',
        'Ophthalmology - Glaucoma Specialist': 'Ophthalmology - Glaucoma Specialist / Oftalmología - Especialista en glaucoma',
        'Ophthalmology Ophthalmic Plastic and Reconstructive Surgery': 'Ophthalmology Ophthalmic Plastic And Reconstructive Surgery / Oftalmologia Cirugia plastica y reconstructiva oftalmica',
        'Ophthalmology Retina Specialist': 'Ophthalmology Retina Specialist / Especialista en Retina de Oftalmología',
        'Optometrist - Corneal and Contact Management': 'Optometrist - Corneal And Contact Management / Optometrista - Gestión corneal y de contac-tos',
        'Optometrist': 'Optometrist / Optometrista',
        'Optometrist - Optometrist': 'Optometrist / Optometrista',
        'Specialist - Specialist': 'Specialist - Specialist / Especialista - Especialista',
        'Technician/Technologist - Optician': 'Technician/Technologist - Optician / Técnico/Tecnólogo - Óptico',
        'Psychology': 'Psychology / Psicología',
        'Spine Surgery': 'Spine Surgery / Cirugía de columna',
        'PrimaryCareProvider': 'Primary Care Provider / Listado de proveedores de atención primaria',
        'SpecialistProvider': 'Specialist Provider / Listado de proveedores especialistas',
        'AncillaryProvider': 'Ancillary Provider / Listado de proveedores auxiliares',
        'VisionProvider': 'Vision Provider / Proveedores de servicios de la visit',
        'Doula': 'Doula / doula',
        'Imaging Center': 'Imaging Center / Centro de Imagenología',
        'Genetics': 'Genetics / Genética',
        'Optometrist - Pediatrics': 'Optometrist - Pediatrics / Optometrista - Pediatría',
        'Family Medicine - Sports Medicine': 'Family Medicine - Sports Medicine / Medicina Familiar - Medicina Deportiva',
        'Endocrinology Diabetes and Metabolism - Internal Medicine': 'Endocrinology Diabetes and Metabolism - Internal Medicine / Endocrinología Diabetes y Metabolismo - Medicina Interna',
        'Advanced Heart Failure and Transplant Cardiology': 'Advanced Heart Failure and Transplant Cardiology / Cardiología avanzada de insuficiencia cardíaca y trasplantes',
        'Cardiac Surgery - Thoracic Surgery': 'Cardiac Surgery - Thoracic Surgery / Cirugía Cardíaca - Cirugía Torácica',
        'Cardiovascular Disease - Hematology Oncology - Nephrology': 'Cardiovascular Disease - Hematology Oncology - Nephrology / Enfermedad Cardiovascular - Hematología Oncología - Nefrología',
        'Cardiovascular Disease - Vascular Surgery': 'Cardiovascular Disease - Vascular Surgery / Enfermedad Cardiovascular - Cirugía Vascular',
        'Child Abuse Pediatrics / Pediatría': 'Child Abuse Pediatrics / Pediatría / Abuso Infantil Pediatría / Pediatría',
        'Critical Care Medicine - Pulmonary Disease': 'Critical Care Medicine - Pulmonary Disease / Medicina de cuidados críticos - enfermedad pulmonar',
        'Epilepsy': 'Epilepsy / Epilepsia',
        'Family Medicine - Pain Medicine': 'Family Medicine - Pain Medicine / Medicina familiar - Medicina del dolor',
        'Neuro Interventional Radiology': 'Neuro Interventional Radiology / Radiología Neuro Intervencionista',
        'Orthopaedics': 'Orthopaedics / Ortopedía',
        'Orthopaedics - Vascular Surgery': 'Orthopaedics - Vascular Surgery / Ortopedia - Cirugía Vascular',
        'Home Visiting Services-HFA': 'Home Visiting Services-HFA / Servicios de visitas domiciliarias-HFA',
        'Internal Medicine - Pulmonary Disease': 'Internal Medicine - Pulmonary Disease / Medicina Interna - Enfermedad Pulmonar',
        'Endocrinology Diabetes and Metabolism - Family Medicine':'Endocrinology Diabetes and Metabolism - Family Medicine / Endocrinología Diabetes y Metabolismo - Medicina Familiar',
        'Colon and Rectal Surgery - Gender Affirming Care': 'Colon and Rectal Surgery - Gender Affirming Care / Cirugía de colon y recto: atención de afirmación de género',
        'Gastroenterology - Internal Medicine': 'Gastroenterology - Internal Medicine / Gastroenterología - Medicina Interna',
        'Gender Affirming Care - Plastic Surgery':  'Gender Affirming Care - Plastic Surgery / Atención de afirmación de género - Cirugía plástica',
        'Hematology Oncology - Vascular Surgery': 'Hematology Oncology - Vascular Surgery / Hematología Oncología - Cirugía Vascular',
        'Internal Medicine - Neurology': 'Internal Medicine - Neurology / Medicina Interna - Neurología',
        'Obstetrics and Gynecology - Urology': 'Obstetrics and Gynecology - Urology / Obstetricia y Ginecología - Urología',
        'Internal Medicine - Specialist - Nephrology': 'Internal Medicine - Specialist - Nephrology / Medicina Interna - Especialista - Nefrología',
        'Obstetrics and Gynecology - Pediatrics': 'Obstetrics and Gynecology - Pediatrics / Obstetricia y Ginecología - Pediatría',
        'Cardiovascular Disease - Internal Medicine': 'Cardiovascular Disease - Internal Medicine / Enfermedad Cardiovascular - Medicina Interna',
        'Internal Medicine - Pediatrics': 'Internal Medicine - Pediatrics / Medicina Interna - Pediatría',
        'Advanced Heart Failure and Transplant Cardiology - Cardiovascular Disease': 'Advanced Heart Failure and Transplant Cardiology - Cardiovascular Disease / Cardiología avanzada de insuficiencia cardíaca y trasplantes - Enfermedad Cardiovascular',
        'Cardiac Electrophysiology - Cardiovascular Disease': 'Cardiac Electrophysiology - Cardiovascular Disease / Electrofisiología cardíaca - Enfermedad Cardiovascular',
        'Colon and Rectal Surgery - Pediatric Surgery': 'Colon and Rectal Surgery - Pediatric Surgery / Cirugía de colon y recto - Cirugía pediátrica',
        'Emergency Medicine - Sports Medicine': 'Emergency Medicine - Sports Medicine / Medicina de emergencia - Medicina deportiva',
        'Family Medicine - Psychiatry': 'Family Medicine - Psychiatry / Medicina familiar - Psiquiatría',
        'Gender Affirming Care - Urology': 'Gender Affirming Care - Urology / Atención de afirmación de género - Urología',
        'Hematology - Medical Oncology': 'Hematology - Medical Oncology / Hematología - Oncología médica',
        'Internal Medicine - Rheumatology': 'Internal Medicine - Rheumatology / Medicina Interna - Reumatología',
        'Pediatric Orthopaedic Surgery - Sports Medicine': 'Pediatric Orthopaedic Surgery - Sports Medicine / Cirugía ortopédica pediátrica - Medicina deportiva',
        'Pediatric Urology - Urology': 'Pediatric Urology - Urology / Urología pediátrica - Urología',
        'Pediatrics - Pediatric Neurology': 'Pediatrics - Pediatric Neurology / Pediatría - Neurología pediátrica',
        'Pulmonary Disease - Sleep Medicine': 'Pulmonary Disease - Sleep Medicine / Enfermedad pulmonar - Medicina del sueño',
        'Pulmonary Disease - Transplant Surgery': 'Pulmonary Disease - Transplant Surgery / Enfermedad pulmonar - Cirugía de trasplante',
        'Family Medicine - Infectious Diseases': 'Family Medicine - Infectious Diseases / Medicina familiar - Enfermedades infecciosas',
        'Infectious Diseases - Internal Medicine': 'Infectious Diseases - Internal Medicine / Enfermedades infecciosas - Medicina interna',
        'Allergy and Immunology - Pediatric Allergy and Immunology': 'Allergy and Immunology - Pediatric Allergy and Immunology / Alergia e inmunología - Alergia e inmunología pediátrica',
        'Family Medicine - Gastroenterology': 'Family Medicine - Gastroenterology / Medicina familiar - Gastroenterología',
        'Internal Medicine - Nephrology': 'Internal Medicine - Nephrology / Medicina interna - Nefrología',
        'Maternal - Fetal Medicine - Reproductive Endocrinology and Infertility': 'Maternal - Fetal Medicine - Reproductive Endocrinology and Infertility / Medicina maternofetal - Endocrinología reproductiva e infertilidad',
        'Internal Medicine - Medical Oncology': 'Internal Medicine - Medical Oncology / Medicina interna - Oncología médica',


    }

    provider_type_dict = {
        'PrimaryCareProvider': 'Primary Care Provider / Proveedores de atención primaria',
        'SpecialistProvider': 'Specialist Provider / Proveedores especialistas',
        'AncillaryProvider': 'Ancillary Provider / Proveedores auxiliares',
        'Pharmacy': 'Pharmacy / Farmacia',
        'VisionProvider': 'Vision Provider / Proveedor de visión'
    }
