class Utils:
    PCP = ['Family Medicine',
           'Internal Medicine',
           'Pediatrics',
           'Ophthalmology',
           'Optometry',
           'Orthopaedic Surgery',
           'Pain Medicine',
           'Physician Assistant',
           'Physician Assistant PCP']

    Specialist_Providers = [
        'Acupuncture', 'Adolescent Medicine',
        'Advanced Heart Failure and Transplant Cardiology',
        'Allergy And Immunology',
        'Anesthesiology',
        'Audiology',
        'Bariatric Surgery',
        'Breast Surgery',
        'Burn Surgery',
        'Cardiac Electrophysiology',
        'Cardiac Surgery',
        'Cardiovascular Disease',
        'Certified Nurse Midwife',
        'Child Abuse Pediatrics',
        'Chiropractic Medicine',
        'Clinical Biochemical Genetics',
        'Clinical Genetics',
        'Clinical Neurophysiology',
        'Colon and Rectal Surgery',
        'Critical Care Medicine',
        'Dermatology',
        'Dermatopathology',
        'Developmental And Behavioral Pediatrics',
        'Emergency Medicine',
        'Endocrinology Diabetes and Metabolism',
        'Family Medicine - Specialist',
        'Female Pelvic Reproductive Surgery',
        'Gastroenterology',
        'General Practice - Specialist',
        'General Practice',
        'General Surgery',
        'Gynecologic Oncology',
        'Gynecology',
        'Hand Surgery',
        'Hematology',
        'Hematology Oncology',
        'Hospice and Palliative Medicine',
        'Infectious Diseases',
        'Internal Medicine - Specialist',
        'Interventional Cardiology',
        'Interventional Radiology',
        'Licensed Dietetic Nutritionist',
        'Maternal - Fetal Medicine',
        'Medical Acupuncture',
        'Medical Genetics',
        'Medical Oncology',
        'Neonatal-Perinatal Medicine',
        'Nephrology',
        'Neurodevelopmental Disabilities',
        'Neurology',
        'Neurosurgery',
        'Nutritionist',
        'Obstetrics and Gynecology',
        'Ophthalmology',
        'Optometry',
        'Oral & Maxillofacial Surgery',
        'Orthopaedic Surgery',
        'Orthopedic Oncology',
        'Otolaryngology',
        'Pain Medicine',
        'Pathology - Anatomic and Clinical',
        'Pediatric Allergy and Immunology',
        'Pediatric Cardiac Surgery',
        'Pediatric Cardiology',
        'Pediatric Clinical Genetics',
        'Pediatric Critical Care Medicine',
        'Pediatric Dermatology',
        'Pediatric Endocrinology',
        'Pediatric Gastroenterology',
        'Pediatric Genetics',
        'Pediatric Hematology-Oncology',
        'Pediatric Infectious Diseases',
        'Pediatric Nephrology',
        'Pediatric Neurodevelopmental Disabilities',
        'Pediatric Neurology',
        'Pediatric Neurosurgery',
        'Pediatric Ophthalmology',
        'Pediatric Orthopaedic Surgery',
        'Pediatric Otolaryngology',
        'Pediatric Plastic And Reconstructive Surgery',
        'Pediatric Pulmonology',
        'Pediatric Rehabilitation Medicine',
        'Pediatric Rheumatology',
        'Pediatric Surgery',
        'Pediatric Transplant Hepatology',
        'Pediatric Urology',
        'Pediatrics - Specialist',
        'Physical Medicine And Rehabilitation',
        'Physician Assistant',
        'Plastic Surgery',
        'Podiatry',
        'Psychiatry',
        'Pulmonary Disease',
        'Preventive Medicine',
        'Radiation Oncology',
        'Registered Dietician',
        'Reproductive Endocrinology and Infertility',
        'Rheumatology',
        'Sleep Medicine',
        'Spinal Cord Injury Medicine',
        'Sports Medicine',
        'Surgical Critical Care',
        'Surgical Oncology',
        'Thoracic Surgery',
        'Transplant Hepatology',
        'Transplant Surgery',
        'Trauma Surgery',
        'Undersea and Hyperbaric Medicine',
        'Urogynecology',
        'Urology',
        'Vascular and Interventional Radiology',
        'Vascular Neurology',
        'Vascular Surgery']

    Ancillary_Provider = [
        'Ambulance & Van Transport',
        'Ambulatory Surgery Center',
        'Cardiac Monitoring',
        'Diabetic Prevention Program',
        'Dialysis',
        'Durable Medical Equipment',
        'Home Health',
        'Hospice',
        'Hospital',
        'Infusion/Injectables',
        'Laboratory',
        'Orthotics & Prosthetics',
        'Pediatric Hospital',
        'Radiology',
        'Rehab Hospital',
        'Rehabilitation',
        'Skilled Nursing Facility',
        'Sleep Center',
        'Urgent Care Centers'
    ]

    Pharmacy = ['Pharmacy']

    Vision_Provider = [
        'Clinic/Center - Federally Qualified Health Center (FQHC)',
        'Eyewear Supplier (Equipment Not The Service)',
        'Eyewear Supplier (Equipment not the service) - Eyewear Supplier (Equipment not the service)',
        'Ophthalmology - Ophthalmology',
        'Ophthalmology - Glaucoma Specialist',
        'Ophthalmology Ophthalmic Plastic and Reconstructive Surgery',
        'Ophthalmology Retina Specialist',
        'Optometrist - Corneal And Contact Management',
        'Optometrist',
        'Optometrist - Optometrist',
        'Technician/Technologist - Optician'
    ]

    Dentaal_Provider = [
        'Specialist - Specialist'
    ]
